[profile.default]
src = "contracts"
script = "scripts"
out = "out"
libs = ["lib"]
test = "test"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
hyperevm = "${HYPEREVM_RPC_URL}"

[etherscan]
hyperevm = { key = "${ETHERSCAN_API_KEY}" }
